- name : setting up app
  ansible.builtin.import_role:
    name: common
    tasks_from: app_setup

- name : setting up java
  ansible.builtin.import_role:
    name: common
    tasks_from: java

- name : setting mysql
  ansible.builtin.import_role:
    name: common
    tasks_from: mysql-setup

- name: systemctl service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd_services