- name: app-setup 
  ansible.builtin.import_role:
    name: common
    tasks_from: app_setup

- name: setting up nodejs 
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs_setup

- name: setting up mongodb
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb_setup

- name: systemctl service 
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd_services
