- name : setting up app
  ansible.builtin.import_role:
    name: common
    tasks_from: app_setup

- name : setting up go
  ansible.builtin.import_role:
    name: common
    tasks_from: go


- name: systemctl service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd_services