- name: create roboshop user
  ansible.builtin.user:
    name: roboshop

- name: Recursively remove app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: make directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: "download {{component}} application"
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazo"naws.com {{component}}.zip"
    dest: /tmp

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    s"rc: "/tmp {{component}}.zip"
    des"t: /app 
    remote_src: yes 