- name: "stop {{component}}"
  tags:
  - deployment
  ansible.builtin.service:
    name: "{{component}}"
    state: stopped

- name: Recursively remove app directory
  tags:
  - deployment
  ansible.builtin.file:
    path: /app
    state: absent

- name: make directory
  tags:
  - deployment
  ansible.builtin.file:
    path: /app
    state: directory

- name: "download {{component}} application"
  tags:
  - deployment
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp

- name: Unarchive a file that is already on the remote machine
  tags:
  - deployment
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: /app 
    remote_src: yes