- name: install golang
  ansible.builtin.dnf:
    name: golang
    state: present

- name: install dependencies
  ansible.builtin.command: "{{item}}"
  loop:
  - go mod init dispatch 
  - go get 
  - go build 
  args: 
    chidr: /app