- name: demon reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: enable and start catalogue 
  ansible.builtin.service: 
    name: catalogue     
    state: started
    enabled: yes
