- name: setting up appsetup
  ansible.builtin.import_role:
    name: common
    tasks_from: app_setup

- name: setting up nodejs 
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs_setup

- name: systemctl services
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd_services